services:
  web:
    build: .
    env_file:
      - .env
    environment:
      - CONNECTION_STRING=${CONNECTION_STRING_DOCKER}
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    command: ["java", "-jar", "/app/todoist-api-1.0.0.jar"]

  db:
    image: postgres
    restart: always
    container_name: todoist-postgres
    environment:
      PGUSER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - dev-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  dev-data:
